### ISSUE TITLE
Ente Auth Sign up flow error 

### ISSUE THREAD

**Issue by sspathare97** [ente-io/ente#1126]
### Description

https://auth.ente.io/verify

```
Something went wrong, please try again {"message":"Network Error","name":"AxiosError","stack":"AxiosError: Network Error\n at c.onerror (https://auth.ente.io/_next/static/chunks/pages/_app-564c63ae00349026.js:36:43534)\n at XMLHttpRequest.r (https://auth.ente.io/_next/static/chunks/pages/_app-564c63ae00349026.js:15:3046)\n at e$.request (https://auth.ente.io/_next/static/chunks/pages/_app-564c63ae00349026.js:36:48504)\n at async s.request (https://auth.ente.io/_next/static/chunks/pages/_app-564c63ae00349026.js:21:36405)\n at async Object.L [as callback] (https://auth.ente.io/_next/static/chunks/pages/verify-bc811bc10bd0facf.js:1:981)\n at async b (https://auth.ente.io/_next/static/chunks/pages/login-97012e6a1b9e828f.js:1:14057)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","X-Client-Package":"io.ente.auth.web"},"data":"{\"email\":\"sspathare97@gmail.com\",\"ott\":\"923859\",\"source\":\"web:\"}","method":"post","url":"https://api.ente.io/users/verify-email"},"code":"ERR_NETWORK","status":null}
```

![auth ente io_verify (1)](https://github.com/ente-io/ente/assets/18231119/5ef6070c-9fcf-443f-a96b-e1e27bb49306)

### What product are you using?

Ente Auth

### What platform are you using?

Web - Chrome

**Comment by ua741** [comment]
Hello,

This should be fixed now. Please feel free to re-open this ticket if you are still facing error during login.
[Releated](https://github.com/ente-io/ente/issues/1120#issuecomment-2002300934)

**Comment by eleaner** [comment]
I seem to be getting exactly the same error when trying to self-host, what could be the reason?
