### ISSUE TITLE
[ente web] Cannot open single images

### ISSUE THREAD

**Issue by roughnecks** [ente-io/ente#1472]
### Description

Hello,

I'm running a self-hosted ente server with external S3. I configured the photos app in my phone and everything checks out.
Then I wanted to also host the web application, so I built it:

`NEXT_PUBLIC_ENTE_ENDPOINT=https://subdomain.mydomain.tld yarn build`
Copied the resulting output dir (/ente/web/apps/photos/out) in my html root and configured nginx to serve those files.

I am able to login, sync all of my previously uploaded pictures, upload new files/folders but anytime I try to open a single photo to visualize it, I get the following errors in chrome's console:

```
framework-2c15c603e130d21e.js:9 TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at q (_app-46598b1bee62328e.js:123:180466)
    at 6487-07f6ba0c6088541f.js:1:44671
    at Object.<anonymous> (6487-07f6ba0c6088541f.js:1:44728)
    at eS (3789-b33fc15f28c5425c.js:114:14867)
    at Object.updateCurrItem (3789-b33fc15f28c5425c.js:114:40873)
    at Object.init (3789-b33fc15f28c5425c.js:114:39545)
    at tD (6487-07f6ba0c6088541f.js:1:44878)
    at 6487-07f6ba0c6088541f.js:1:42297
    at uU (framework-2c15c603e130d21e.js:9:84107)
    at oV (framework-2c15c603e130d21e.js:9:113153)
a9	@	framework-2c15c603e130d21e.js:9
a.componentDidCatch.t.callback	@	framework-2c15c603e130d21e.js:9
lW	@	framework-2c15c603e130d21e.js:9
uX	@	framework-2c15c603e130d21e.js:9
e	@	framework-2c15c603e130d21e.js:9
(anonymous)	@	framework-2c15c603e130d21e.js:9
oU	@	framework-2c15c603e130d21e.js:9
oP	@	framework-2c15c603e130d21e.js:9
r8	@	framework-2c15c603e130d21e.js:9
(anonymous)	@	framework-2c15c603e130d21e.js:9
main-4e13a7d13a527750.js:1 TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at q (_app-46598b1bee62328e.js:123:180466)
    at 6487-07f6ba0c6088541f.js:1:44671
    at Object.<anonymous> (6487-07f6ba0c6088541f.js:1:44728)
    at eS (3789-b33fc15f28c5425c.js:114:14867)
    at Object.updateCurrItem (3789-b33fc15f28c5425c.js:114:40873)
    at Object.init (3789-b33fc15f28c5425c.js:114:39545)
    at tD (6487-07f6ba0c6088541f.js:1:44878)
    at 6487-07f6ba0c6088541f.js:1:42297
    at uU (framework-2c15c603e130d21e.js:9:84107)
    at oV (framework-2c15c603e130d21e.js:9:113153)
Z	@	main-4e13a7d13a527750.js:1
fn	@	main-4e13a7d13a527750.js:1
componentDidCatch	@	main-4e13a7d13a527750.js:1
a.componentDidCatch.t.callback	@	framework-2c15c603e130d21e.js:9
lW	@	framework-2c15c603e130d21e.js:9
uX	@	framework-2c15c603e130d21e.js:9
e	@	framework-2c15c603e130d21e.js:9
(anonymous)	@	framework-2c15c603e130d21e.js:9
oU	@	framework-2c15c603e130d21e.js:9
oP	@	framework-2c15c603e130d21e.js:9
r8	@	framework-2c15c603e130d21e.js:9
(anonymous)	@	framework-2c15c603e130d21e.js:9
main-4e13a7d13a527750.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
Z	@	main-4e13a7d13a527750.js:1
fn	@	main-4e13a7d13a527750.js:1
componentDidCatch	@	main-4e13a7d13a527750.js:1
a.componentDidCatch.t.callback	@	framework-2c15c603e130d21e.js:9
lW	@	framework-2c15c603e130d21e.js:9
uX	@	framework-2c15c603e130d21e.js:9
e	@	framework-2c15c603e130d21e.js:9
(anonymous)	@	framework-2c15c603e130d21e.js:9
oU	@	framework-2c15c603e130d21e.js:9
oP	@	framework-2c15c603e130d21e.js:9
r8	@	framework-2c15c603e130d21e.js:9
(anonymous)	@	framework-2c15c603e130d21e.js:9
```

These are debug logs from the web app:

```
[2024-04-17T11:00:15.400Z] [info] Starting ente-photos-web git 020ed59d4 uid 1580559962386438
[2024-04-17T11:00:31.534Z] [info] Opening Ml DB
[2024-04-17T11:00:32.592Z] [info] Syncing location entities localEntitiesCount: 0
[2024-04-17T11:00:32.602Z] [info] Syncing location entities syncTime: 0
[2024-04-17T11:00:32.802Z] [info] Syncing embeddings localCount: 0
[2024-04-17T11:00:32.813Z] [info] Syncing onnx-clip model's embeddings sinceTime: 0
[2024-04-17T11:00:37.088Z] [info] [10000326] getSlideData called for thumbnail:false sourceLoaded:undefined fetching:undefined
[2024-04-17T11:00:37.097Z] [info] [10000326] doesn't have thumbnail
[2024-04-17T11:00:37.119Z] [info] [10000326] calling invalidateCurrItems for thumbnail msrc :true
[2024-04-17T11:00:37.137Z] [info] [10000326] getSlideData called for thumbnail:true sourceLoaded:false fetching:undefined
[2024-04-17T11:00:37.152Z] [info] [10000326] new file src request
[2024-04-17T11:00:37.167Z] [info] download attempted for file id 10000326
[2024-04-17T11:00:37.180Z] [error] updating photoswipe after msrc url update failed: TypeError: Cannot read properties of undefined (reading 'toLowerCase')
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at q (https://subdomain.mydomain.com/_next/static/chunks/pages/_app-46598b1bee62328e.js:123:180466)
    at https://subdomain.mydomain.com/_next/static/chunks/6487-07f6ba0c6088541f.js:1:44671
    at Object.<anonymous> (https://subdomain.mydomain.com/_next/static/chunks/6487-07f6ba0c6088541f.js:1:44728)
    at eS (https://subdomain.mydomain.com/_next/static/chunks/3789-b33fc15f28c5425c.js:114:14867)
    at Object.updateCurrZoomItem (https://subdomain.mydomain.com/_next/static/chunks/3789-b33fc15f28c5425c.js:114:40433)
    at Object.updateSize (https://subdomain.mydomain.com/_next/static/chunks/3789-b33fc15f28c5425c.js:114:41823)
    at q (https://subdomain.mydomain.com/_next/static/chunks/6487-07f6ba0c6088541f.js:1:65365)
[2024-04-17T11:00:37.191Z] [info] [10000326] file download already in progress
[2024-04-17T11:00:37.212Z] [info] Starting ente-photos-web git 020ed59d4 uid 1580559962386438
[2024-04-17T11:00:37.316Z] [info] DownloadManager already initialized
[2024-04-17T11:00:37.617Z] [info] Syncing location entities localEntitiesCount: 0
[2024-04-17T11:00:37.628Z] [info] Syncing location entities syncTime: 0
[2024-04-17T11:00:37.742Z] [info] Syncing embeddings localCount: 0
[2024-04-17T11:00:37.753Z] [info] Syncing onnx-clip model's embeddings sinceTime: 0
[2024-04-17T11:00:38.310Z] [info] [10000326] calling invalidateCurrItems for src, source loaded :true
[2024-04-17T11:00:38.321Z] [info] [10000326] getSlideData called for thumbnail:true sourceLoaded:true fetching:true
[2024-04-17T11:00:38.331Z] [info] [10000326] source already loaded
[2024-04-17T11:00:38.342Z] [error] updating photoswipe after src url update failed: TypeError: Cannot read properties of undefined (reading 'toLowerCase')
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at q (https://subdomain.mydomain.com/_next/static/chunks/pages/_app-46598b1bee62328e.js:123:180466)
    at https://subdomain.mydomain.com/_next/static/chunks/6487-07f6ba0c6088541f.js:1:44671
    at Object.<anonymous> (https://subdomain.mydomain.com/_next/static/chunks/6487-07f6ba0c6088541f.js:1:44728)
    at eS (https://subdomain.mydomain.com/_next/static/chunks/3789-b33fc15f28c5425c.js:114:14867)
    at Object.updateCurrZoomItem (https://subdomain.mydomain.com/_next/static/chunks/3789-b33fc15f28c5425c.js:114:40433)
    at Object.updateSize (https://subdomain.mydomain.com/_next/static/chunks/3789-b33fc15f28c5425c.js:114:41823)
    at q (https://subdomain.mydomain.com/_next/static/chunks/6487-07f6ba0c6088541f.js:1:66979)
[2024-04-17T11:05:38.330Z] [info] Syncing location entities localEntitiesCount: 0
[2024-04-17T11:05:38.348Z] [info] Syncing location entities syncTime: 0
[2024-04-17T11:05:38.544Z] [info] Syncing embeddings localCount: 0
[2024-04-17T11:05:38.561Z] [info] Syncing onnx-clip model's embeddings sinceTime: 0
[2024-04-17T11:10:37.226Z] [info] [10000326] getSlideData called for thumbnail:true sourceLoaded:true fetching:true
[2024-04-17T11:10:37.238Z] [info] [10000326] source already loaded
[2024-04-17T11:10:37.255Z] [error] Unhandled error: TypeError: Cannot read properties of undefined (reading 'toLowerCase')
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at q (https://subdomain.mydomain.com/_next/static/chunks/pages/_app-46598b1bee62328e.js:123:180466)
    at https://subdomain.mydomain.com/_next/static/chunks/6487-07f6ba0c6088541f.js:1:44671
    at Object.<anonymous> (https://subdomain.mydomain.com/_next/static/chunks/6487-07f6ba0c6088541f.js:1:44728)
    at eS (https://subdomain.mydomain.com/_next/static/chunks/3789-b33fc15f28c5425c.js:114:14867)
    at Object.updateCurrZoomItem (https://subdomain.mydomain.com/_next/static/chunks/3789-b33fc15f28c5425c.js:114:40433)
    at Object.updateSize [as resize] (https://subdomain.mydomain.com/_next/static/chunks/3789-b33fc15f28c5425c.js:114:41823)
    at Object.handleEvent (https://subdomain.mydomain.com/_next/static/chunks/3789-b33fc15f28c5425c.js:114:40223)
[2024-04-17T11:10:37.268Z] [error] Unhandled error: TypeError: Cannot read properties of undefined (reading 'toLowerCase')
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at q (https://subdomain.mydomain.com/_next/static/chunks/pages/_app-46598b1bee62328e.js:123:180466)
    at https://subdomain.mydomain.com/_next/static/chunks/6487-07f6ba0c6088541f.js:1:44671
    at Object.<anonymous> (https://subdomain.mydomain.com/_next/static/chunks/6487-07f6ba0c6088541f.js:1:44728)
    at eS (https://subdomain.mydomain.com/_next/static/chunks/3789-b33fc15f28c5425c.js:114:14867)
    at Object.updateCurrZoomItem (https://subdomain.mydomain.com/_next/static/chunks/3789-b33fc15f28c5425c.js:114:40433)
    at Object.updateSize [as resize] (https://subdomain.mydomain.com/_next/static/chunks/3789-b33fc15f28c5425c.js:114:41823)
    at Object.handleEvent (https://subdomain.mydomain.com/_next/static/chunks/3789-b33fc15f28c5425c.js:114:40223)
[2024-04-17T11:10:37.293Z] [info] [10000326] getSlideData called for thumbnail:true sourceLoaded:true fetching:true
[2024-04-17T11:10:37.303Z] [info] [10000326] source already loaded
[2024-04-17T11:10:37.313Z] [error] Unhandled error: TypeError: Cannot read properties of undefined (reading 'toLowerCase')
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at q (https://subdomain.mydomain.com/_next/static/chunks/pages/_app-46598b1bee62328e.js:123:180466)
    at https://subdomain.mydomain.com/_next/static/chunks/6487-07f6ba0c6088541f.js:1:44671
    at Object.<anonymous> (https://subdomain.mydomain.com/_next/static/chunks/6487-07f6ba0c6088541f.js:1:44728)
    at eS (https://subdomain.mydomain.com/_next/static/chunks/3789-b33fc15f28c5425c.js:114:14867)
    at Object.updateCurrZoomItem (https://subdomain.mydomain.com/_next/static/chunks/3789-b33fc15f28c5425c.js:114:40433)
    at Object.updateSize [as resize] (https://subdomain.mydomain.com/_next/static/chunks/3789-b33fc15f28c5425c.js:114:41823)
    at Object.handleEvent (https://subdomain.mydomain.com/_next/static/chunks/3789-b33fc15f28c5425c.js:114:40223)
[2024-04-17T11:10:37.324Z] [error] Unhandled error: TypeError: Cannot read properties of undefined (reading 'toLowerCase')
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at q (https://subdomain.mydomain.com/_next/static/chunks/pages/_app-46598b1bee62328e.js:123:180466)
    at https://subdomain.mydomain.com/_next/static/chunks/6487-07f6ba0c6088541f.js:1:44671
    at Object.<anonymous> (https://subdomain.mydomain.com/_next/static/chunks/6487-07f6ba0c6088541f.js:1:44728)
    at eS (https://subdomain.mydomain.com/_next/static/chunks/3789-b33fc15f28c5425c.js:114:14867)
    at Object.updateCurrZoomItem (https://subdomain.mydomain.com/_next/static/chunks/3789-b33fc15f28c5425c.js:114:40433)
    at Object.updateSize [as resize] (https://subdomain.mydomain.com/_next/static/chunks/3789-b33fc15f28c5425c.js:114:41823)
    at Object.handleEvent (https://subdomain.mydomain.com/_next/static/chunks/3789-b33fc15f28c5425c.js:114:40223)
[2024-04-17T11:10:38.380Z] [info] Syncing location entities localEntitiesCount: 0
[2024-04-17T11:10:38.391Z] [info] Syncing location entities syncTime: 0
[2024-04-17T11:10:38.509Z] [info] Syncing embeddings localCount: 0
[2024-04-17T11:10:38.518Z] [info] Syncing onnx-clip model's embeddings sinceTime: 0
[2024-04-17T11:10:39.118Z] [info] DownloadManager already initialized
[2024-04-17T11:10:39.869Z] [info] Syncing location entities localEntitiesCount: 0
[2024-04-17T11:10:39.905Z] [info] Syncing location entities syncTime: 0
[2024-04-17T11:10:40.024Z] [info] Syncing embeddings localCount: 0
[2024-04-17T11:10:40.034Z] [info] Syncing onnx-clip model's embeddings sinceTime: 0
[2024-04-17T11:10:50.571Z] [info] Downloading logs
```

### Version

git commit 020ed59d4053889ecccbd734b368144b40017465

### What product are you using?

Ente Photos

### What platform are you using?

Web - Chrome

**Comment by mnvr** [comment]
Please do not open issues related to self hosting. 

You can ask in discussions if you wish though in this particular case, I tried reproducing this, and cannot. You can try with the git commit that is deployed on our production instance and see if you're still facing the issue - that'd indicate some sort of likely local misconfiguration or a missing `yarn install`.

To use the git commit that is deployed on production, you can checkout the `deploy/photos` branch.

**Comment by roughnecks** [comment]
Thanks, moving the discussion here: https://github.com/ente-io/ente/discussions/1476
