### ISSUE TITLE
Docker compose error 

### ISSUE THREAD

**Issue by aruiplex** [ente-io/ente#1912]
### Description

Hi! I pull the docker image and up all services by docker compose following the [guide](https://github.com/ente-io/ente/blob/main/server/docs/docker.md).

The Docker compose gives this error:

```
$ docker compose up -d
[+] Running 6/6
 ✔ Network ente_internal             Created                                                                                                                                      0.1s 
 ✔ Container ente-minio-1            Started                                                                                                                                      0.1s 
 ✔ Container ente-postgres-1         Healthy                                                                                                                                      0.1s 
 ✔ Container ente-minio-provision-1  Started                                                                                                                                      0.1s 
 ✔ Container ente-museum-1           Started                                                                                                                                      0.0s 
 ✔ Container ente-socat-1            Created                                                                                                                                      0.0s 
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: can't get final child's PID from pipe: EOF: unknown
```

Here are the docker logs:

```
$ docker compose logs
ente-minio-provision-1  | Added `h0` successfully.
ente-minio-provision-1  | Bucket created successfully `b2-eu-cen`.
ente-minio-provision-1  | Bucket created successfully `wasabi-eu-central-2-v3`.
ente-minio-1            | MinIO Object Storage Server
ente-minio-provision-1  | Bucket created successfully `scw-eu-fr-v3`.
ente-museum-1           | INFO[0000]main.go:92 main Booting up local server with commit #26e17d8464736acc747c1b35c65af194172a245c 
ente-museum-1           | INFO[0000]main.go:765 setupDatabase Setting up db                                
ente-museum-1           | INFO[0000]main.go:772 setupDatabase Connected to DB                              
ente-museum-1           | INFO[0000]main.go:777 setupDatabase Pinged DB                                    
ente-museum-1           | INFO[0000]main.go:786 setupDatabase Loaded migration scripts                     
ente-museum-1           | PANI[0000]main.go:788 setupDatabase Dirty database version 80. Fix and force version. 
ente-museum-1           | panic: (*logrus.Entry) 0xc0011b4620
ente-museum-1           | 
ente-museum-1           | goroutine 1 [running]:
ente-museum-1           | github.com/sirupsen/logrus.Entry.log({0xc0004dbb20, 0xc000fd2cc0, {0x0, 0x0, 0x0}, 0x0, 0x0, {0x0, 0x0}, 0x0, ...}, ...)
ente-museum-1           |       /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x31a
ente-museum-1           | github.com/sirupsen/logrus.(*Entry).Log(0xc0011b41c0, 0x0, {0xc00113f0b0?, 0x1f43da0?, 0xc000350620?})
ente-museum-1           |       /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xa8
ente-minio-1            | Copyright: 2015-2024 MinIO, Inc.
ente-minio-1            | License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
ente-minio-1            | Version: RELEASE.2024-05-27T19-17-46Z (go1.22.3 linux/amd64)
ente-minio-1            | 
ente-minio-1            | API: http://172.23.0.2:3200  http://127.0.0.1:3200 
ente-minio-1            | WebUI: http://172.23.0.2:3201 http://127.0.0.1:3201 
ente-minio-1            | 
ente-minio-1            | Docs: https://min.io/docs/minio/linux/index.html
ente-postgres-1         | 
ente-museum-1           | github.com/sirupsen/logrus.(*Logger).Log(0xc0004dbb20, 0x0, {0xc00113f0b0, 0x1, 0x1})
ente-postgres-1         | PostgreSQL Database directory appears to contain a database; Skipping initialization
ente-museum-1           |       /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:193 +0x65
ente-museum-1           | github.com/sirupsen/logrus.(*Logger).Panic(...)
ente-museum-1           |       /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:234
ente-museum-1           | github.com/sirupsen/logrus.Panic(...)
ente-museum-1           |       /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/exported.go:129
ente-museum-1           | main.setupDatabase()
ente-museum-1           |       /etc/ente/cmd/museum/main.go:788 +0x2d5
ente-museum-1           | main.main()
ente-museum-1           |       /etc/ente/cmd/museum/main.go:112 +0x3b2
ente-minio-1            | Status:         1 Online, 0 Offline. 
ente-minio-1            | STARTUP WARNINGS:
ente-minio-1            | - The standard parity is set to 0. This can lead to data loss.
ente-minio-1            | 
ente-minio-1            |  You are running an older version of MinIO released 22 hours before the latest release 
ente-minio-1            |  Update: Run `mc admin update ALIAS` 
ente-minio-1            | 
ente-minio-1            | 
ente-postgres-1         | 
ente-postgres-1         | 2024-05-29 06:41:52.503 UTC [1] LOG:  starting PostgreSQL 12.19 (Debian 12.19-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
ente-postgres-1         | 2024-05-29 06:41:52.503 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
ente-postgres-1         | 2024-05-29 06:41:52.503 UTC [1] LOG:  listening on IPv6 address "::", port 5432
ente-postgres-1         | 2024-05-29 06:41:52.512 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
ente-postgres-1         | 2024-05-29 06:41:52.530 UTC [27] LOG:  database system was shut down at 2024-05-29 06:41:45 UTC
ente-postgres-1         | 2024-05-29 06:41:52.538 UTC [1] LOG:  database system is ready to accept connections
```

The service and Prometheus are not up.

### Version

docker image ghcr.io/ente-io/server on 20240528 (sry I do not know how to check the specific version))

### What product are you using?

Ente Photos

### What platform are you using?

Server

**Comment by mnvr** [comment]
Please do not open issues related to self hosting. It is mentioned in the README, __and__ in the bug report template, requesting you to not do that.

<img width="436" alt="Screenshot 2024-05-29 at 12 35 49" src="https://github.com/ente-io/ente/assets/24503581/7796bc57-5573-4387-a594-d1cabf48513f">

About the error, you can see it in the logs

> PANI[0000]main.go:788 setupDatabase Dirty database version 80. Fix and force version. 

Something when you were trying to set this up caused your DB to be in an unexpected state. If you delete the docker compose cluster and bring it up again, it should work fine.
