### ISSUE TITLE
Import from Aegis - Could not parse

### ISSUE THREAD

**Issue by K0-RR** [ente-io/ente#1934]
### Description

When I try to import plain or encrypted Aegis backup/export it fails saying it couldn't parse the file

### Version

3.0.4

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - Android, Mobile - FDroid

**Comment by K0-RR** [comment]
I do have a token for Steam

```
 [LockScreen] [INFO] [2024-06-02 21:12:19.075382] initiatingState
 [LockScreen] [INFO] [2024-06-02 21:12:19.092599] Showing lock screen postFrameInit 1717355539092
 [AuthUtil] [INFO] [2024-06-02 21:12:19.092878] Requesting authentication
 [LockScreen] [INFO] [2024-06-02 21:12:21.996623] AppLifecycleState.hidden
 [LockScreen] [INFO] [2024-06-02 21:12:21.996856] AppLifecycleState.inactive
 [LockScreen] [INFO] [2024-06-02 21:12:22.093732] AppLifecycleState.resumed
 [AegisImport] [SEVERE] [2024-06-02 21:12:32.229664] exception while processing for aegis
⤷ type: _Exception
⤷ error: Exception: Invalid OTP type
⤷ trace: #0      _processAegisExportFile (package:ente_auth/ui/settings/data/import/aegis_import.dart:151)
<asynchronous suspension>
#1      _pickAegisJsonFile (package:ente_auth/ui/settings/data/import/aegis_import.dart:68)
<asynchronous suspension>
#2      showAegisImportInstruction (package:ente_auth/ui/settings/data/import/aegis_import.dart:51)
<asynchronous suspension>
#3      ImportService.initiateImport (package:ente_auth/ui/settings/data/import/import_service.dart:35)
<asynchronous suspension>
#4      ImportCodePage.build.<anonymous closure>.<anonymous closure> (package:ente_auth/ui/settings/data/import_page.dart:108)
<asynchronous suspension>
#5      _MenuItemWidgetState._onTap.<anonymous closure> (package:ente_auth/ui/components/menu_item_widget.dart:222)
<asynchronous suspension>
#6      _MenuItemWidgetState._onTap (package:ente_auth/ui/components/menu_item_widget.dart:221)
<asynchronous suspension>

 [LockScreen] [INFO] [2024-06-02 21:12:35.451875] Showing lock screen tapUnlock 1717355555451
 [AuthUtil] [INFO] [2024-06-02 21:12:35.452029] Requesting authentication
 [LockScreen] [INFO] [2024-06-02 21:12:35.542897] AppLifecycleState.inactive
 [LockScreen] [FINEST] [2024-06-02 21:12:37.541119] LockScreen Result true 1717355555451
 [LockScreen] [INFO] [2024-06-02 21:12:37.573273] AppLifecycleState.resumed
 [LockScreen] [INFO] [2024-06-02 21:12:37.869582] disposing
```

**Comment by ua741** [comment]
Can you please try the latest version (v3.0.6) and let us know if you are still facing similar issue?

**Comment by Deanosim** [comment]
v3.0.6 seems to have fixed it for me, thanks devs <3
