### ISSUE TITLE
Ente Auth deb and appimage won't launch latest version 3.0.6

### ISSUE THREAD

**Issue by linuxosd** [ente-io/ente#1978]
### Description

Neither the .deb nor appimage of the latest version of ente auth v3.0.6 will launch on Ubuntu 24.04.

### Version

3.0.6

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Linux

**Comment by alessandroberna** [comment]
I'm facing the same issue 

Attempting to run ente_auth after installing it from the .deb yields a rather long list of failed asserts: 
<details><summary>Logs</summary>
<p>

```
** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlBinaryMessenger *fl_engine_get_binary_messenger(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlTextureRegistrar *fl_engine_get_texture_registrar(FlEngine *): assertion 'FL_IS_ENGINE(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlPluginRegistrar *fl_plugin_registrar_new(FlView *, FlBinaryMessenger *, FlTextureRegistrar *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: invalid (NULL) pointer instance

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: g_signal_handler_find: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: invalid (NULL) pointer instance

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: invalid (NULL) pointer instance

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: invalid (NULL) pointer instance

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: invalid (NULL) pointer instance

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: invalid (NULL) pointer instance

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: invalid (NULL) pointer instance

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: invalid (NULL) pointer instance

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: invalid (NULL) pointer instance

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.758: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.758: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.759: invalid (NULL) pointer instance

(ente_auth:117272): GLib-GObject-CRITICAL **: 21:58:46.759: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.759: FlView *fl_plugin_registrar_get_view(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

(ente_auth:117272): Gtk-CRITICAL **: 21:58:46.759: gtk_container_forall: assertion 'GTK_IS_CONTAINER (container)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.759: FlBinaryMessenger *fl_plugin_registrar_get_messenger(FlPluginRegistrar *): assertion 'FL_IS_PLUGIN_REGISTRAR(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.759: FlMethodChannel *fl_method_channel_new(FlBinaryMessenger *, const gchar *, FlMethodCodec *): assertion 'FL_IS_BINARY_MESSENGER(messenger)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.759: void fl_method_channel_set_method_call_handler(FlMethodChannel *, FlMethodChannelMethodCallHandler, gpointer, GDestroyNotify): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.759: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.759: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.759: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.759: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.759: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed

** (ente_auth:117272): CRITICAL **: 21:58:46.759: void fl_method_channel_invoke_method(FlMethodChannel *, const gchar *, FlValue *, GCancellable *, GAsyncReadyCallback, gpointer): assertion 'FL_IS_METHOD_CHANNEL(self)' failed
```
</p>
</details> 

This also happens when building from source, the issue seems related to flutter/flutter#144873
Downgrading flutter similarly to what has been suggested on other repos (ubuntu/yaru.dart#903) should work as a temporary solution. 
It seems that it would be enough to rever commit b753c47

As for the appimage, attempting to start it on my distribution (Arch Linux) gives out the following error:
`./ente_auth: symbol lookup error: /usr/lib/libtiff.so.6: undefined symbol: jpeg12_write_raw_data, version LIBJPEG_8.0`.
This was happening on the previous version too: #1801

**Comment by ua741** [comment]
Can you please upgrade to version 3.0.7? Let us know if you still face the same issue after the upgrade

**Comment by linuxosd** [comment]
> Can you please upgrade to version 3.0.7? Let us know if you still face the same issue after the upgrade

The deb version of 3.0.7 works. I can't speak for the appimage as I haven't tried it.

**Comment by clrizzi** [comment]
> Can you please upgrade to version 3.0.7? Let us know if you still face the same issue after the upgrade

I just updated to the last version (3.0.7) and for me, the problem persists on both: .deb and .AppImage.

![Captura de tela de 2024-06-04 12-09-15](https://github.com/ente-io/ente/assets/12688807/ce98d998-1770-4192-9894-daaa542b5206)


I have the following error messages in the terminal:

```flutter:  [ente_logging] [INFO] [2024-06-04 11:47:29.262888] log file for today: File: '/home/clrizzi/.local/share/ente_auth/logs/2024-6-4.txt' with prefix 
flutter: [ente_logging] [INFO] [2024-06-04 11:47:29.262888] app version: '3.0.7+307'
flutter: [ente_logging] [INFO] [2024-06-04 11:47:29.262888] 
flutter:  [main] [INFO] [2024-06-04 11:47:29.262951] Starting app in foreground
flutter:  [Configuration] [INFO] [2024-06-04 11:47:29.268404] Skipping temp folder clear

** (ente_auth:61768): WARNING **: 11:47:29.275: libsecret_error: Failed to unlock the keyring
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Libsecret error, Failed to unlock the keyring, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
<asynchronous suspension>


** (ente_auth:61768): WARNING **: 11:47:29.278: libsecret_error: Failed to unlock the keyring
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Libsecret error, Failed to unlock the keyring, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
<asynchronous suspension>


** (ente_auth:61768): WARNING **: 11:47:29.281: libsecret_error: Failed to unlock the keyring
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Libsecret error, Failed to unlock the keyring, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
<asynchronous suspension>


** (ente_auth:61768): WARNING **: 11:47:29.284: libsecret_error: Failed to unlock the keyring
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Libsecret error, Failed to unlock the keyring, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
<asynchronous suspension>
#2      Configuration._initOfflineAccount (package:ente_auth/core/configuration.dart:100)
<asynchronous suspension>
#3      Configuration.init (package:ente_auth/core/configuration.dart:96)
<asynchronous suspension>
#4      _init (package:ente_auth/main.dart:150)
<asynchronous suspension>
#5      _runInForeground.<anonymous closure> (package:ente_auth/main.dart:93)
<asynchronous suspension>
#6      SuperLogging.main (package:ente_auth/core/logging/super_logging.dart:201)
<asynchronous suspension>
#7      _runWithLogs (package:ente_auth/main.dart:122)
<asynchronous suspension>
#8      _runInForeground (package:ente_auth/main.dart:91)
<asynchronous suspension>
#9      main (package:ente_auth/main.dart:82)
<asynchronous suspension>
```

**Comment by alessandroberna** [comment]
> Can you please upgrade to version 3.0.7? Let us know if you still face the same issue after the upgrade

The .deb now works correctly, i updated the AUR package to the new version 

The appimage still gives out the same error:
```
berna@ArchMain ~/repos % ./ente-auth-v3.0.7-x86_64.AppImage 
./ente_auth: symbol lookup error: /usr/lib/libtiff.so.6: undefined symbol: jpeg12_write_raw_data, version LIBJPEG_8.0
```

**Comment by carlosV2** [comment]
I'm having the same error. When running on the terminal I get:
```
❯ ./ente-auth-v3.0.8-x86_64.AppImage 
./ente_auth: symbol lookup error: /usr/lib/libtiff.so.6: undefined symbol: jpeg12_write_raw_data, version LIBJPEG_8.0
```

I'm on Arch Linux.

**Comment by neeraj-pilot** [comment]
This should be fixed now. Please retest with the latest Auth AppImage [v4.4.23](https://github.com/ente-io/ente/releases/tag/auth-v4.4.23)?

The current AppImage packaging changed how runtime libraries are loaded. If it still fails, please share:
- exact AppImage filename/version
- distro and desktop session, e.g. X11 or Wayland
- terminal output from running the AppImage
- whether `./ente-auth-...AppImage --appimage-extract && ./squashfs-root/enteauth` works

**Comment by ua741** [comment]
Please update to the latest version and share logs if the issue persists. We’ve made several Linux packaging fixes, so we’re closing older issues that are related to that.
