### ISSUE TITLE
[Auth] android app crashes a lot

### ISSUE THREAD

**Issue by Farajo001** [ente-io/ente#3081]
### Description

Whenever I try to edit or delete an authentication code the app crashes. I don't even know why this happens to me on even Google Authenticator, which is one of the reasons why I switched (as well as their shady business) but for whatever reason I'm trying to edit two authentication codes because they're two different accounts for the same platform and I want to also delete a duplicated code because the old one doesn't work anymore and it just crashes every single time. I have a Moto E5 Play Go edition Pettyl running stock ROM Android 8.1 Go.

### Version

3.1.2

### What product are you using?

Ente Auth

### What platform are you using?

Mobile - FDroid

**Comment by skyGtm** [comment]
I think i have similar crash in Auth app.
App version: [auth-v4.0.3-beta.5](https://github.com/ente-io/ente/releases/tag/auth-v4.0.3-beta.5)
Android version : 7.0
CPU : Arm-v7a

Steps:
1. Add 2FA details of an account.
2. Try to click "Edit" or "QR" button. Both causes this crash. 

Crash Log captured by Scoop:
`FATAL EXCEPTION: main
Process: io.ente.auth.independent, PID: 16858
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at androidx.appcompat.app.h.e0(AppCompatDelegateImpl.java:406)
	at androidx.appcompat.app.h.k0(AppCompatDelegateImpl.java:5)
	at androidx.appcompat.app.h.I(AppCompatDelegateImpl.java:1)
	at androidx.appcompat.app.m.setContentView(AppCompatDialog.java:1)
	at androidx.appcompat.app.AlertController.e(AlertController.java:7)
	at androidx.appcompat.app.c.onCreate(AlertDialog.java:6)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:524)
	at android.app.Dialog.show(Dialog.java:385)
	at androidx.fragment.app.q.e1(DialogFragment.java:11)
	at androidx.fragment.app.s.D1(Fragment.java:18)
	at androidx.fragment.app.r0.t(FragmentStateManager.java:34)
	at androidx.fragment.app.r0.m(FragmentStateManager.java:74)
	at androidx.fragment.app.l0.d0(FragmentManager.java:42)
	at androidx.fragment.app.l0.j1(FragmentManager.java:92)
	at androidx.fragment.app.l0.a0(FragmentManager.java:22)
	at androidx.fragment.app.l0$f.run(FragmentManager.java:4)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)`

**Comment by neeraj-pilot** [comment]
@skyGtm @Farajo001 Are you still facing this crash in the latest version?

**Comment by ua741** [comment]
Closing due to no response. Please create a new issue with logs if you are still facing this problem.
