### ISSUE TITLE
failed to generate thumbnails for certain HEIC files

### ISSUE THREAD

**Issue by ahxxm** [ente-io/ente#3493]
### Description

I'm uploading them from Desktop, there are 2 types of error logs 

```log
[2024-09-27T18:00:56+09:00] [rndr] [error] Got error event from worker: {"event":{"isTrusted":true},"name":"heic-convert-worker"}
[2024-09-27T18:00:58+09:00] [rndr] [error] Web thumbnail creation failed: Error: HEIF processing error
    at ente://app/_next/static/chunks/9251.16df205f0c2cd8cd.js:1:1673
    at gA.<anonymous> (ente://app/_next/static/chunks/c87b801d.41d2403723d3f507.js:24:14621)

[2024-09-27T18:01:12+09:00] [rndr] [error] Web thumbnail creation failed: RuntimeError: memory access out of bounds
    at wasm://wasm/00318632:wasm-function[75]:0x3ff1
    at wasm://wasm/00318632:wasm-function[43]:0x1f5f
    at wasm://wasm/00318632:wasm-function[1146]:0x95e16
    at Object.heif_context_read_from_memory (eval at Ia (ente://app/_next/static/chunks/c87b801d.41d2403723d3f507.js:3:36482), <anonymous>:9:10)
    at gI.decode (ente://app/_next/static/chunks/c87b801d.41d2403723d3f507.js:24:15166)
    at e (ente://app/_next/static/chunks/9251.16df205f0c2cd8cd.js:1:1894)
    at async one (ente://app/_next/static/chunks/9251.16df205f0c2cd8cd.js:1:2090)
    at async i (ente://app/_next/static/chunks/9251.16df205f0c2cd8cd.js:1:837)
    at async one (ente://app/_next/static/chunks/9251.16df205f0c2cd8cd.js:1:1070)
    at async c (ente://app/_next/static/chunks/8284.b75bbb7689af4b7c.js:1:419)
[2024-09-27T18:01:14+09:00] [rndr] [info] Uploaded IMG_3873.HEIC with result 7 (UPLOADED_WITH_STATIC_THUMBNAIL)
```

These images are from different sources, Samsung/Xiaomi, and some are converted from DSLR jpeg, all but xiaomi failures seem pretty random, i.e. for a same source, some failed and some succeeded.
* DSLR jpg converted using imagemagick: 550 ok, 229 failed
* samsung: 40 ok, 589 failed
* xiaomi: all failed

All images are viewable from Google Photos and Windows 11 Photos, and can be converted to jpg using ImageMagick 7.1.1.25. I'd be glad to provide some samples 

### Version

v1.7.4

### What product are you using?

Ente Photos

### What platform are you using?

Desktop - Windows

**Comment by mnvr** [comment]
Possibly same as https://github.com/ente-io/ente/issues/3391#issuecomment-2367183704

**Comment by ahxxm** [comment]
oh, yeah and all iphone photos failed to generate thumbnails, I once set it to save as HEIC in a month.. I'll try with other failures after 1.7.5 release and report again

**Comment by ahxxm** [comment]
upgraded to 1.7.5, tried mobile HEIC and converted DSLR HEIC, all uploaded successfully, though the device name doesn't show up, this should be a minor display issue because I can download and use exiftool/md5sum to confirm

![{3BA4D06C-6279-4677-8083-E535A50076D4}](https://github.com/user-attachments/assets/36a53002-8adc-47f6-9ce7-bd1ea96e0bb5)

convert (back) to jpg and upload

![{F6F9603D-94B5-46DA-9D91-3F71E453D215}](https://github.com/user-attachments/assets/a676e476-6ac9-4101-98af-a8d47b8815ae)

origin heic
