### ISSUE TITLE
Out of memory on android 15

### ISSUE THREAD

**Issue by r-vdp** [ente-io/ente#3803]
I'm getting the following crash repeatedly since I updated my phone to android 15 this morning:
```
type: crash
osVersion: google/caiman/caiman:15/AP3A.241005.015/2024102100:user/release-keys
flags: dev options enabled
package: io.ente.photos:949
process: io.ente.photos
processUptime: 3369770 + 368 ms
installer: com.aurora.store

java.lang.OutOfMemoryError: Failed to allocate a 200540176 byte allocation with 100663296 free bytes and 123MB until OOM, target footprint 508135264, growth limit 536870912
	at nd.q.d(StandardMessageCodec.java:2)
	at nd.q.g(StandardMessageCodec.java:28)
	at nd.q.f(StandardMessageCodec.java:3)
	at nd.q.g(StandardMessageCodec.java:9)
	at nd.q.f(StandardMessageCodec.java:3)
	at nd.r.a(StandardMethodCodec.java:3)
	at nd.j$a.a(MethodChannel.java:1)
	at bd.c.l(DartMessenger.java:2)
	at bd.c.m(DartMessenger.java:4)
	at bd.c.i(Unknown Source:0)
	at bd.b.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8736)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

I'm running grapheneos on a pixel 9 pro, so I should definitely have plenty of memory available.

The crashes usually happen when I'm not actually using the app, so it's crashing while the app is running in the background.

**Comment by ua741** [comment]
Please update to the latest version. Feel free to comment here again if you are still facing this issue. Thanks!
