### ISSUE TITLE
Cannot select file to import in the flatpak version

### ISSUE THREAD

**Issue by CoutHi** [ente-io/ente#3828]
### Description

When you try to import from a file in the flatpak version, it errors out with the following log:

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Couldn't find the executable zenity in the path.

Zenity is installed on my PC but I don't think you do it that way in flatpak applications anyway, I believe there is a portal for it.

### Version

4.0.3

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Linux

**Comment by shzhe02** [comment]
I'm having the same issue but getting a different log output.

Here's the output I got:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      State.setState (package:flutter/src/widgets/framework.dart:1223)
#1      _ButtonChildWidgetState._onTapUp.<anonymous closure> (package:ente_auth/ui/components/buttons/button_widget.dart:511)
#2      new Future.delayed.<anonymous closure> (dart:async/future.dart:431)
#3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
#5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
```

Steps taken:
1. Download Ente Auth from Flathub
2. Run the app with `flatpak run io.ente.auth`
3. Enter the Ente app and select "Use without backups"
4. Select "Import codes"
5. Select "Ente Encrypted export"

I've also attempted to select all of the other import options, but none of them seem to work either (although I haven't verified that they produce the same error message in the console).

### Version

4.0.3 (flatpak version, but the console logs say `app version: '4.2.2+422` so I'm not entirely sure which is right)

### What platform are you using?

Desktop - Linux (Fedora Kinoite 41)

**Comment by iaissaoui** [comment]
I have this exact issue

` [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Couldn't find the executable zenity in the path.
#0      isExecutableOnPath (package:file_picker/src/utils.dart:60)
<asynchronous suspension>
#1      FilePickerLinux._getPathToExecutable (package:file_picker/src/linux/file_picker_linux.dart:127)
<asynchronous suspension>
#2      FilePickerLinux.pickFiles (package:file_picker/src/linux/file_picker_linux.dart:29)
<asynchronous suspension>
#3      _pickImportFile (package:ente_auth/ui/settings/data/import/plain_text_import.dart:100)
<asynchronous suspension>
`

zenity is installed

`Package zenity-3.32.0-8.el9.x86_64 is already installed.`

distro:

rhel 9

**Comment by kolon0** [comment]
> I'm having the same issue but getting a different log output.
> 
> Here's the output I got:
> 
> ```
> [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
> #0      State.setState (package:flutter/src/widgets/framework.dart:1223)
> #1      _ButtonChildWidgetState._onTapUp.<anonymous closure> (package:ente_auth/ui/components/buttons/button_widget.dart:511)
> #2      new Future.delayed.<anonymous closure> (dart:async/future.dart:431)
> #3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
> #4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
> #5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
> #6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
> ```
> 
> Steps taken:
> 
> 1. Download Ente Auth from Flathub
> 2. Run the app with `flatpak run io.ente.auth`
> 3. Enter the Ente app and select "Use without backups"
> 4. Select "Import codes"
> 5. Select "Ente Encrypted export"
> 
> I've also attempted to select all of the other import options, but none of them seem to work either (although I haven't verified that they produce the same error message in the console).
> 
> ### Version
> 4.0.3 (flatpak version, but the console logs say `app version: '4.2.2+422'` so I'm not entirely sure which is right)
> 
> ### What platform are you using?
> Desktop - Linux (Fedora Kinoite 41)

I also have the same error: https://github.com/ente-io/ente/issues/4991#issuecomment-2692324318

**Comment by ua741** [comment]
Is this issue still happening on the latest version?

**Comment by shzhe02** [comment]
> Is this issue still happening on the latest version?

I believe it has since been fixed. Just tested again, and both plaintext and encrypted imports work on Flatpak install 

Platform: Desktop - Linux (Fedora Kinoite 44)
Ente Auth version: 4.4

Great work!

**Comment by ua741** [comment]
Thanks for confirming.
