### ISSUE TITLE
Mobile Photos app crashing with protobuf error

### ISSUE THREAD

**Issue by nazarewk** [ente-io/ente#3907]
### Description

for at least 2 weeks app crashes while uploading anything, uploads between 0 and 5 photos then crashes. I'm on latest GrapheneOS and ente photos 0.9.53 from F-Droid
```
type: crash
osVersion: google/husky/husky:15/AP3A.241005.015/2024103100:user/release-keys
flags: dev options enabled
package: io.ente.photos.fdroid:953, targetSdk 34
process: io.ente.photos.fdroid
processUptime: 5804 + 225 ms
installer: com.machiav3lli.fdroid

ai.onnxruntime.OrtException: Error code - ORT_INVALID_PROTOBUF - message: Load model from /data/user/0/io.ente.photos.fdroid/files/assets/models_ente_io_mobileclip_s2_text_opset18_quant_onnx failed:Protobuf parsing failed.
	at ai.onnxruntime.OrtSession.createSession(Native Method)
	at ai.onnxruntime.OrtSession.<init>(OrtSession.java:3)
	at ai.onnxruntime.OrtEnvironment.createSession(OrtEnvironment.java:4)
	at ai.onnxruntime.OrtEnvironment.createSession(OrtEnvironment.java:2)
	at na.a.f(OnnxDartPlugin.kt:5)
	at na.a.a(OnnxDartPlugin.kt:1)
	at na.a$d.l(OnnxDartPlugin.kt:8)
	at vb.a.g(ContinuationImpl.kt:4)
	at oc.d1.run(DispatchedTask.kt:22)
	at tc.s$a.run(LimitedDispatcher.kt:1)
	at vc.k.run(Tasks.kt:1)
	at vc.a.T(CoroutineScheduler.kt:1)
	at vc.a$c.d(CoroutineScheduler.kt:4)
	at vc.a$c.p(CoroutineScheduler.kt:4)
	at vc.a$c.run(CoroutineScheduler.kt:1)
	Suppressed: tc.k: [v2{Cancelling}@32b092c, Dispatchers.IO]
```

### Version

v0.9.53

### What product are you using?

Ente Photos

### What platform are you using?

Mobile - FDroid

**Comment by nazarewk** [comment]
Actually it always crashes, not just when uploading.

**Comment by nazarewk** [comment]
FYI: doesn't seem to crash after clearing whole application's data and logging in again.
