### ISSUE TITLE
Migration From Google Photos Fails -  Cannot read properties of undefined (reading 'accessedThroughSharedURL')

### ISSUE THREAD

**Issue by fifafu** [ente-io/ente#4077]
### Description

After uploading about half of my photos via the macOS Desktop app I got a "Something went" wrong, and now Ente doesn't seem to continue uploading.

Is there anything I can do?

In the log I found this error:

```
[2024-11-18T09:28:23+01:00] [rndr] [info] Uploading 160653 files
[2024-11-18T09:28:23+01:00] [rndr] [error] Upload failed: TypeError: Cannot read properties of undefined (reading 'accessedThroughSharedURL')
    at eH.updateExistingFilesAndCollections (ente://app/_next/static/chunks/1928-b5fb196cbbcc4ace.js:1:313119)
    at eH.uploadItems (ente://app/_next/static/chunks/1928-b5fb196cbbcc4ace.js:1:312267)
    at eR (ente://app/_next/static/chunks/1928-b5fb196cbbcc4ace.js:1:89016)
    at ente://app/_next/static/chunks/1928-b5fb196cbbcc4ace.js:1:88686
    at eT (ente://app/_next/static/chunks/1928-b5fb196cbbcc4ace.js:1:88697)
    at eS (ente://app/_next/static/chunks/1928-b5fb196cbbcc4ace.js:1:88593)
[2024-11-18T09:28:23+01:00] [rndr] [error] Failed to upload files: TypeError: Cannot read properties of undefined (reading 'accessedThroughSharedURL')
    at eH.updateExistingFilesAndCollections (ente://app/_next/static/chunks/1928-b5fb196cbbcc4ace.js:1:313119)
    at eH.uploadItems (ente://app/_next/static/chunks/1928-b5fb196cbbcc4ace.js:1:312267)
    at eR (ente://app/_next/static/chunks/1928-b5fb196cbbcc4ace.js:1:89016)
    at ente://app/_next/static/chunks/1928-b5fb196cbbcc4ace.js:1:88686
    at eT (ente://app/_next/static/chunks/1928-b5fb196cbbcc4ace.js:1:88697)
    at eS (ente://app/_next/static/chunks/1928-b5fb196cbbcc4ace.js:1:88593)
[2024-11-18T09:28:23+01:00] Update for version 1.7.6 is not available (latest version: 1.7.6, downgrade is disallowed).
```

### Version

v1.7.6

### What product are you using?

Ente Photos

### What platform are you using?

Desktop - macOS

**Comment by mnvr** [comment]
The app seems to be in a undefined state. It would be good to figure out how it got there (the relevant logs from when the  "Something went wrong" originally happened).

Meanwhile, to reset the app, have you tried restarting it? If restarting doesn't help, you could try a logout and login. This will cause your import to start again from the beginning, but if you drag and drop the same folders again, the app will skip over already uploaded file, so there shouldn't be any duplicates.

**Comment by fifafu** [comment]
Thanks I'll try logout and login!

These were the logs right when the last file was successfully uploaded. I restarted the app after I got the "something went wrong" then the error from the initial post above was logged
```
[2024-11-18T07:58:44+01:00] [rndr] [info] Uploaded IMG_4564.HEIC with result 6 (UPLOADED)
[2024-11-18T07:58:45+01:00] [rndr] [info] Uploading IMG_4554.HEIC
[2024-11-18T07:58:45+01:00] [rndr] [info] Uploaded IMG_4563.HEIC with result 6 (UPLOADED)
[2024-11-18T07:58:45+01:00] [rndr] [info] Uploading IMG_4553.HEIC
[2024-11-18T07:58:46+01:00] [rndr] [info] download attempted for file id 107026111
[2024-11-18T07:58:46+01:00] [rndr] [info] download attempted for file id 107026109
[2024-11-18T07:58:46+01:00] [rndr] [info] Uploaded IMG_4553.HEIC with result 8 (ADDED_SYMLINK)
[2024-11-18T07:58:46+01:00] [rndr] [info] Uploading IMG_4552.HEIC
[2024-11-18T07:58:46+01:00] [rndr] [info] Uploaded IMG_4552.HEIC with result 8 (ADDED_SYMLINK)
[2024-11-18T07:58:46+01:00] [rndr] [info] Uploading IMG_4551.HEIC
[2024-11-18T07:58:46+01:00] [rndr] [info] download attempted for file id 107026105
[2024-11-18T07:58:46+01:00] [rndr] [info] download attempted for file id 107026094
[2024-11-18T07:58:47+01:00] [rndr] [info] Uploaded IMG_4551.HEIC with result 8 (ADDED_SYMLINK)
[2024-11-18T07:58:47+01:00] [rndr] [info] Uploading IMG_4550.HEIC
[2024-11-18T07:58:47+01:00] [rndr] [info] Uploaded IMG_4550.HEIC with result 8 (ADDED_SYMLINK)
[2024-11-18T07:58:47+01:00] [rndr] [info] Uploading IMG_4549.HEIC
[2024-11-18T07:58:48+01:00] [rndr] [info] Uploaded IMG_4549.HEIC with result 8 (ADDED_SYMLINK)
[2024-11-18T07:58:48+01:00] [rndr] [info] Uploading IMG_4548.HEIC
[2024-11-18T07:58:48+01:00] [rndr] [info] download attempted for file id 107026075
[2024-11-18T07:58:48+01:00] [rndr] [info] download attempted for file id 107026069
[2024-11-18T09:28:19+01:00] [main] [info] Starting ente-photos-desktop 1.7.6
[2024-11-18T09:28:19+01:00] [main] [info] Running on { platform: 'darwin', osRelease: '24.1.0', systemVersion: '15.1.0' }
[2024-11-18T09:28:19+01:00] Checking for update
[2024-11-18T09:28:19+01:00] [rndr] [info] Starting ente-photos-web git bc70689 uid 1580559962504282
[2024-11-18T09:28:19+01:00] [rndr] [info] DownloadManager already initialized
[2024-11-18T09:28:22+01:00] [rndr] [info] Folder watch deduced 0 events
[2024-11-18T09:28:22+01:00] [rndr] [info] Resuming pending of upload of 160653 items
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Takeout with id 1580559963111496
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Google Fotos with id 1580559963111497
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Auswahl Portraits Familie with id 1580559963111498
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album auswahl portraits with id 1580559963111499
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Bilder auf denen Max besoffen ausschaut with id 1580559963111500
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Lena & Arne ❤️🤵🏼‍♂️👰🏼‍♀️ with id 1580559963111501
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album urlaub Chiemgau  with id 1580559963111502
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 1970 with id 1580559963111503
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 1979 with id 1580559963111504
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Baby Fotos Philipp with id 1580559963111505
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Unbenannt(7) with id 1580559963111506
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Unbenannt(11) with id 1580559963111507
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album joolz with id 1580559963111508
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 2010 with id 1580559963111509
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 2017 with id 1580559963111510
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 2021 with id 1580559963111511
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 2019 with id 1580559963111512
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Unbenannt(12) with id 1580559963111513
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Unbenannt(4) with id 1580559963111514
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Max & Philipp with id 1580559963111515
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 2018 with id 1580559963111516
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Immer wieder Samstags Fotogruppe with id 1580559963111517
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Renate 60 with id 1580559963111518
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Tanne & Soff 👰❤️🤵🏻 with id 1580559963111519
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 2020 with id 1580559963111520
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 2016 with id 1580559963111521
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Kreta with id 1580559963111522
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 2011 with id 1580559963111523
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 2002 with id 1580559963111524
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 2005 with id 1580559963111525
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album 2. Geburtstag Max with id 1580559963111526
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Lena & Arne ❤️👰🏻🤵🏼‍♂️❤️ with id 1580559963111527
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Unbenannt with id 1580559963111528
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Papierkorb with id 1580559963111529
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 2004 with id 1580559963111530
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 2003 with id 1580559963111531
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Unbenannt(15) with id 1580559963111532
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Unbenannt(3) with id 1580559963111533
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Unbenannt(9) with id 1580559963111534
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Auerbergstraße 6 Bau with id 1580559963111535
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Super Sommer Sause 2023 with id 1580559963111536
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 1997 with id 1580559963111537
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Videos with id 1580559963111538
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 1999 with id 1580559963111539
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album hochzeit Rebecca with id 1580559963111540
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Achensee with id 1580559963111541
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album sammlung with id 1580559963111542
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Failed Videos with id 1580559963111543
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Tümpelplatte with id 1580559963111544
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album KLOPPOFF with id 1580559963111545
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album weihnachten 2021 with id 1580559963111546
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album urlaub urlaub urlaub (1) with id 1580559963111547
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Micha JGA with id 1580559963111548
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album weihnachten 2020 with id 1580559963111549
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 2014 with id 1580559963111550
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 2013 with id 1580559963111551
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Unbenannt(14) with id 1580559963111552
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Unbenannt(2) with id 1580559963111553
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 2022 with id 1580559963111554
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Unbenannt(8) with id 1580559963111555
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album augen with id 1580559963111556
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album nachschlagen with id 1580559963111557
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album auerdult with id 1580559963111558
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 2023 with id 1580559963111559
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 2024 with id 1580559963111560
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Unbenannt(1) with id 1580559963111561
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 2012 with id 1580559963111562
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Lena 33 with id 1580559963111563
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 2015 with id 1580559963111564
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album rita 30 with id 1580559963111565
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Unbenannt(13) with id 1580559963111566
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Unbenannt(5) with id 1580559963111567
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 2008 with id 1580559963111568
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Rückblick auf 2009 with id 1580559963111569
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 2006 with id 1580559963111570
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Babybauch with id 1580559963111571
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 2001 with id 1580559963111572
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Unbenannt(6) with id 1580559963111573
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Unbenannt(10) with id 1580559963111574
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 2007 with id 1580559963111575
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Photos from 2009 with id 1580559963111576
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Taufe Mathilda with id 1580559963111577
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album urlaub urlaub urlaub  with id 1580559963111578
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Archiv with id 1580559963111579
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album Jakob with id 1580559963111580
[2024-11-18T09:28:23+01:00] [rndr] [info] Found existing album familienfotos with id 1580559963111581
[2024-11-18T09:28:23+01:00] [rndr] [info] Uploading 160653 files
[2024-11-18T09:28:23+01:00] [rndr] [error] Upload failed: TypeError: Cannot read properties of undefined (reading 'accessedThroughSharedURL')
    at eH.updateExistingFilesAndCollections (ente://app/_next/static/chunks/1928-b5fb196cbbcc4ace.js:1:313119)
    at eH.uploadItems (ente://app/_next/static/chunks/1928-b5fb196cbbcc4ace.js:1:312267)
    at eR (ente://app/_next/static/chunks/1928-b5fb196cbbcc4ace.js:1:89016)
    at ente://app/_next/static/chunks/1928-b5fb196cbbcc4ace.js:1:88686
    at eT (ente://app/_next/static/chunks/1928-b5fb196cbbcc4ace.js:1:88697)
    at eS (ente://app/_next/static/chunks/1928-b5fb196cbbcc4ace.js:1:88593)
[2024-11-18T09:28:23+01:00] [rndr] [error] Failed to upload files: TypeError: Cannot read properties of undefined (reading 'accessedThroughSharedURL')
    at eH.updateExistingFilesAndCollections (ente://app/_next/static/chunks/1928-b5fb196cbbcc4ace.js:1:313119)
    at eH.uploadItems (ente://app/_next/static/chunks/1928-b5fb196cbbcc4ace.js:1:312267)
    at eR (ente://app/_next/static/chunks/1928-b5fb196cbbcc4ace.js:1:89016)
    at ente://app/_next/static/chunks/1928-b5fb196cbbcc4ace.js:1:88686
    at eT (ente://app/_next/static/chunks/1928-b5fb196cbbcc4ace.js:1:88697)
    at eS (ente://app/_next/static/chunks/1928-b5fb196cbbcc4ace.js:1:88593)
[2024-11-18T09:28:23+01:00] Update for version 1.7.6 is not available (latest version: 1.7.6, downgrade is disallowed).
[2024-11-18T09:28:27+01:00] [rndr] [info] download attempted for file id 107027735
[2024-11-18T09:28:27+01:00] [rndr] [info] download attempted for file id 107027731
[2024-11-18T09:28:27+01:00] [rndr] [info] download attempted for file id 107027730
[2024-11-18T09:28:27+01:00] [rndr] [info] download attempted for file id 107027729
[2024-11-18T09:28:29+01:00] [rndr] [info] download attempted for file id 107027719
```

**Comment by fifafu** [comment]
I'll try logout & login - app restart did not help, actually the error above was only logged after restarting the app.

These were the last logs that appeared at the time of "something went wrong"
It seems to haven't uploaded anything after the "ADDED_SYMLINK" logs.

```

[2024-11-18T07:58:44+01:00] [rndr] [info] Uploaded IMG_4564.HEIC with result 6 (UPLOADED)
[2024-11-18T07:58:45+01:00] [rndr] [info] Uploading IMG_4554.HEIC
[2024-11-18T07:58:45+01:00] [rndr] [info] Uploaded IMG_4563.HEIC with result 6 (UPLOADED)
[2024-11-18T07:58:45+01:00] [rndr] [info] Uploading IMG_4553.HEIC
[2024-11-18T07:58:46+01:00] [rndr] [info] download attempted for file id 107026111
[2024-11-18T07:58:46+01:00] [rndr] [info] download attempted for file id 107026109
[2024-11-18T07:58:46+01:00] [rndr] [info] Uploaded IMG_4553.HEIC with result 8 (ADDED_SYMLINK)
[2024-11-18T07:58:46+01:00] [rndr] [info] Uploading IMG_4552.HEIC
[2024-11-18T07:58:46+01:00] [rndr] [info] Uploaded IMG_4552.HEIC with result 8 (ADDED_SYMLINK)
[2024-11-18T07:58:46+01:00] [rndr] [info] Uploading IMG_4551.HEIC
[2024-11-18T07:58:46+01:00] [rndr] [info] download attempted for file id 107026105
[2024-11-18T07:58:46+01:00] [rndr] [info] download attempted for file id 107026094
[2024-11-18T07:58:47+01:00] [rndr] [info] Uploaded IMG_4551.HEIC with result 8 (ADDED_SYMLINK)
[2024-11-18T07:58:47+01:00] [rndr] [info] Uploading IMG_4550.HEIC
[2024-11-18T07:58:47+01:00] [rndr] [info] Uploaded IMG_4550.HEIC with result 8 (ADDED_SYMLINK)
[2024-11-18T07:58:47+01:00] [rndr] [info] Uploading IMG_4549.HEIC
[2024-11-18T07:58:48+01:00] [rndr] [info] Uploaded IMG_4549.HEIC with result 8 (ADDED_SYMLINK)
[2024-11-18T07:58:48+01:00] [rndr] [info] Uploading IMG_4548.HEIC
[2024-11-18T07:58:48+01:00] [rndr] [info] download attempted for file id 107026075
[2024-11-18T07:58:48+01:00] [rndr] [info] download attempted for file id 107026069
```
