### ISSUE TITLE
Photos: Desktop client 

### ISSUE THREAD

**Issue by taivlam** [ente-io/ente#4087]
### Description

1. Attempt to turn on machine learning on Ente Photos Desktop.
    - UX path: Open Ente Photos Desktop > Click on hamburger menu > Click on "Machine learning", under "Labs" > Toggle switch to "Enabled" for machine learning
2. Try to leave the desktop client open, only for it to stay on 0 out of `total number of items`.
3. Open Ente Photos on Android and navigate to the machine learning settings to turn machine learning on.
    - UX path: Open Ente Photos Android > Tap on hamburger menu > Tap on "General" > Tap on "Advanced" > Tap on "Machine learning" > Find both the "Enabled" and "Local indexing" switches toggled on already.
4. Observe Ente Photos Android get past 0 items completed and the whole initialization of machine learning come to an end.

This is despite the warning in the Ente Photos mobile apps that it's better to use desktop to initialize machine learning, instead of the mobile app.  (For this, I plugged in my Android device and used Wi-Fi during this process.)

### System info
* Ente Photos on Android
    * GrapheneOS release `2024101200`
    * Pixel 5a (`barbet`)
    * Ente Photos `0.9.58` from F-Droid
    * Logs: [2024-11-18.log](https://github.com/user-attachments/files/17807084/2024-11-18.log)
* Ente Photos on Linux
    * Manjaro Unstable
    * Ente Photos `1.7.6-1` from the AUR ([`ente-desktop-bin`](https://aur.archlinux.org/packages/ente-desktop-bin))
    * Logs: [ente.log](https://github.com/user-attachments/files/17806993/ente.log)

### Version

1.7.6-1

### What product are you using?

Ente Photos

### What platform are you using?

Desktop - Linux

**Comment by mnvr** [comment]
Also, if it happens again, it would be helpful to have a traceroute to see if there is some issue that can be spotted there
```
traceroute files.ente.io
```

**Comment by stevs84** [comment]
I have the same issue, but the Indexing / Machine Learning is successful on the Desktop App (Mac).
On my Mobile Phone (Android App) and Tablet (Android App) the process is not starting and all my elements have the status "pending".

I get also some strange error in my log:
`WARN[20109]main.go:984 urlSanitizer Unknown API: /files/data/status-diff         
INFO[20109]request_logger.go:116 func5 outgoing                                      client_ip=xxx.xxx.xxx.xxx client_pkg=io.ente.photos client_version=0.9.58 h_latency=218.317µs latency_time=218.317µs query= req_body= req_id=b6eb4ed5-ae9a-4775-9b79-4e8c4d0b5ae1 req_method=POST req_uri=/files/data/status-diff status_code=404 ua=Ente Photos/0.9.58 (Android 15; Pixel 9 Pro XL; komodo; arm64-v8a) user_id=0
`

**Comment by taivlam** [comment]
@mnvr I forgot to mention, but I forgot to state originally that both clients were connected to Mullvad VPN.  For some reason (not sure if this is related, but), the [DAITA](https://mullvad.net/en/vpn/daita)-only servers are very much more likely to cause webpages to receive Cloudflare ray captchas than running Mullvad using default settings.

Also, I'll try using `traceroute` the next time this happens.

**Comment by iadaz** [comment]
I am using the latest Windows desktop. I left it running overnight to perform the machine learning. Looks like it stopped at about 30%. Last thing in log:

```
[2024-12-07T03:59:46+00:00] [rndr] [info] download attempted for file id 75803122
[2024-12-07T03:59:58+00:00] [rndr] [info] download attempted for file id 75803069
[2024-12-07T04:00:17+00:00] [rndr] [info] download attempted for file id 75803058
[2024-12-07T04:00:17+00:00] [rndr] [info] download attempted for file id 75803046
[2024-12-07T04:00:46+00:00] [rndr] [error] Unhandled promise rejection: TypeError: Failed to fetch
    at w (ente://app/_next/static/chunks/pages/_app-bef3745976cbf66f.js:2:341836)
    at async j (ente://app/_next/static/chunks/pages/_app-bef3745976cbf66f.js:2:344209)
    at async eW (ente://app/_next/static/chunks/pages/_app-bef3745976cbf66f.js:2:352514)
    at async eZ (ente://app/_next/static/chunks/pages/_app-bef3745976cbf66f.js:2:352431)
```

My router reboots at 04:00 daily so it looks like the process has no retry mechanism for a network interruption. Closing the app completely and starting again allowed it to carry on.

**Comment by mnvr** [comment]
@iadaz Thank you for the logs. The issue you're describing seems like a separate edge case that OP, but either way, I've fixed this in https://github.com/ente-io/ente/pull/4439.

**Comment by ButlerJoseph** [comment]
I'm experiencing this issue on Windows Desktop (version 1.7.14) with no errors appearing in the logs. The application functions correctly on my Android device, and I'm using the Ente.io hosted instance.

This is the traceroute:
```
Tracing route to files.ente.io [104.18.7.241]
over a maximum of 30 hops:

  1     5 ms     3 ms     3 ms  192.168.0.1
  2     *        *        *     Request timed out.
  3    13 ms    14 ms    12 ms  80.255.197.228
  4     *        *        *     Request timed out.
  5     *        *        *     Request timed out.
  6    16 ms    16 ms    15 ms  tele-ic-7-ae2-0.network.virginmedia.net [62.253.175.34]
  7     *        *        *     Request timed out.
  8    17 ms    16 ms    19 ms  141.101.71.95
  9    16 ms    15 ms    16 ms  104.18.7.241
```

**Comment by mnvr** [comment]
@ButlerJoseph The original issue in this thread was fixed in https://github.com/ente-io/ente/pull/4439, so this seems like a different issue. However, you say there are no errors in the logs, which is curious. Usually, if ML indexing is not working, it is for some few files where the image processing pipeline on desktop is not able to process the file but the mobile image processing pipeline can (or vice versa) - e.g. that is likely the issue that @DanteMS ran into when they were describing that 99% on one platform and 100% on the other. 

But in those cases, there should be some errors in the logs. If there are no errors, and you've double checked that ML is enabled in Sidebar > Preferences, then maybe another thing to try is to logout from the desktop app and login again. The logout and login will reset any local state that the desktop app has about files that have been indexed, including files it is skipping over because they were marked as permanently failed. So after login, and verifying that ML is enabled in Preferences, the desktop app should attempt to reindex any pending files.

Note that files which have already been indexed on one platform don't need to be indexed again, so in such cases you'll not see anything in the logs, the client will just pull the already uploaded encrypted indexes.

**Comment by taivlam** [comment]
I haven't experience my originally described issue for a while, so I'll close this issue.  (I'll reopen this if I ever experience this again.)
