### ISSUE TITLE
Ente Photos crashes when used as the Google camera gallery application

### ISSUE THREAD

**Issue by metamacro** [ente-io/ente#4116]
### Description

With [Gcam services provider photos](https://github.com/lukaspieper/Gcam-Services-Provider) you can use a gallery app other than Google Photos with Google Camera.
When Ente Photos is selected as the default one it immediately crashes when clicking on the gallery.
The stock AOSP Gallery application works if set as default.

All system and application updates are up to date.

OS: GrapheneOS

Crash log:
```
type: crash
osVersion: google/caiman/caiman:15/AP3A.241105.008/2024111800:user/release-keys
flags: dev options enabled
package: io.ente.photos.fdroid:958, targetSdk 34
process: io.ente.photos.fdroid
processUptime: 199 + 234 ms
installer: com.android.packageinstaller

java.lang.NullPointerException
	at na.b.c(MediaExtensionPlugin.kt:10)
	at na.b.f(MediaExtensionPlugin.kt:1)
	at na.b.a(Unknown Source:0)
	at na.a.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```
4m

### Version

0.9.58

### What product are you using?

Ente Photos

### What platform are you using?

Mobile - Android, Mobile - FDroid

**Comment by pbarney** [comment]
I am experiencing this same problem. Have you found any solutions?

**Comment by piorpiedev** [comment]
Bump

<details>
<summary>My info & crash logs:</summary>

Ente Photos version 1.2.11

com.google.android.GoogleCamera
versionCode 68469120
version 9.9.106.773153235.19

```
type: crash
osVersion: google/tegu/tegu:16/BP2A.250805.005/2025102601:user/release-keys
package: io.ente.photos.independent:1211, targetSdk 35
process: io.ente.photos.independent
processUptime: 533 + 433 ms
installer: dev.imranr.obtainium.fdroid

java.lang.NullPointerException
	at B0.o.run(Unknown Source:1372)
	at android.os.Handler.handleCallback(Handler.java:995)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:248)
	at android.os.Looper.loop(Looper.java:338)
	at android.app.ActivityThread.main(ActivityThread.java:9111)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
```

</details>

**Comment by Qxji** [comment]
I am using the "photosonly" one on grapheneos and while ente does not crash it does not open the single image - it opens the overview for all images (the page that shows up when you start the app basically).

**Comment by ua741** [comment]
This should be fixed in latest app v1.3.44. Will close it once the rollout for that version is complete.

**Comment by laurenspriem** [comment]
This should be fixed in the last v1.3.44 release, do let us know if the issue still occurs!

Since that release it should open on the home gallery, potentially asking to select an album to back it up to. I've just merged [another improvement](https://github.com/ente-io/ente/pull/10536) for it to main, so on the next release (~2 weeks from now) it should open on the photo viewer of the most recent taken photo.

**Comment by piorpiedev** [comment]
Can confirm that it doesn't crash anymore, and opens the app asking to select an album

**Comment by laurenspriem** [comment]
Great! On next release it will open the photo viewer on the most recent taken photo
