### ISSUE TITLE
Ente Auth not opening

### ISSUE THREAD

**Issue by Cool-Game-Dev** [ente-io/ente#4220]
### Description

I'm currently using Arch Linux on the KDE desktop. I downloaded the `ente-auth-bin` AUR package, but when attempting to run it, nothing happens. When running in the terminal, i get the following errors:
```
$ enteauth

** (io.ente.auth:6518): CRITICAL **: 18:24:55.490: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (io.ente.auth:6518): CRITICAL **: 18:24:55.491: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (io.ente.auth:6518): CRITICAL **: 18:24:55.492: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (io.ente.auth:6518): CRITICAL **: 18:24:55.492: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found


** (io.ente.auth:6518): CRITICAL **: 18:24:55.493: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
```

When run with sudo, I get this: 
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Libsecret error, Failed to unlock the keyring, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
<asynchronous suspension>
#2      Configuration._initOfflineAccount (package:ente_auth/core/configuration.dart:99)
<asynchronous suspension>
#3      Configuration.init (package:ente_auth/core/configuration.dart:95)
<asynchronous suspension>
#4      _init (package:ente_auth/main.dart:163)
<asynchronous suspension>
#5      _runInForeground.<anonymous closure> (package:ente_auth/main.dart:106)
<asynchronous suspension>
#6      SuperLogging.main (package:ente_auth/core/logging/super_logging.dart:199)
<asynchronous suspension>
#7      _runWithLogs (package:ente_auth/main.dart:135)
<asynchronous suspension>
#8      _runInForeground (package:ente_auth/main.dart:104)
<asynchronous suspension>
#9      main (package:ente_auth/main.dart:83)
<asynchronous suspension>
```

### Version

v4.1.0

### What product are you using?

Ente Auth

### What platform are you using?

Desktop - Linux

**Comment by Cool-Game-Dev** [comment]
UPDATE: I fixed this by installing Gnome-keyring and by doing [this](https://wiki.archlinux.org/title/GNOME/Keyring#PAM_step). This also removes the need to use sudo.
