### ISSUE TITLE
People search and content search most recent results are months old

### ISSUE THREAD

**Issue by desoter** [ente-io/ente#654]
On linux appimage, I have enabled both ML and Face recognition.

After full sync and indexes update, the most recent results shown for people and content (e.g. "cat", "car") are of 1st November.
Instead, Magic search provide updated results.

In the log I find this error every time a new photo is uploaded:
`[2024-01-20T17:30:57+01:00] [info]  [MLService] Got file:  38499647
[2024-01-20T17:30:57+01:00] [info]  loaded blazeFaceModel:  webgl
[2024-01-20T17:30:57+01:00] [info]  error: Error Failed to link vertex and fragment shaders. 
                msg: ml detection failed 
                Error: Failed to link vertex and fragment shaders.
    at Object.g (ente://app/_next/static/chunks/6315-3f2a78a62dcf473c.js:10205:2254)
    at l.createProgram (ente://app/_next/static/chunks/6315-3f2a78a62dcf473c.js:2429:5204)
    at Object.i (ente://app/_next/static/chunks/6315-3f2a78a62dcf473c.js:2444:528)
    at ente://app/_next/static/chunks/eea4aac7-cbf6764279272ffb.js:16:12541
    at w.getAndSaveBinary (ente://app/_next/static/chunks/eea4aac7-cbf6764279272ffb.js:16:13294)
    at w.runWebGLProgram (ente://app/_next/static/chunks/eea4aac7-cbf6764279272ffb.js:16:12516)
    at w.uploadToGPU (ente://app/_next/static/chunks/eea4aac7-cbf6764279272ffb.js:16:14838)
    at ente://app/_next/static/chunks/eea4aac7-cbf6764279272ffb.js:16:12078
    at Array.map (<anonymous>)
    at w.runWebGLProgram (ente://app/_next/static/chunks/eea4aac7-cbf6764279272ffb.js:16:11620)`

Attaching log of latest app start, thanks!

[ente.log](https://github.com/ente-io/photos-desktop/files/13998657/ente.log)

**Comment by laurenspriem** [comment]
@jerriclynsjohn You should be able to already do that on the latest mobile release. Any changes you make there will be synced to desktop.

**Comment by laurenspriem** [comment]
Closing this issue since the original message regarded the old system that's no longer in use. Please open a new issue if anyone experiences any problems.
